### ISSUE TITLE
variable-font-helper.web.app - Fine Tune check box - What does it do?

### ISSUE THREAD

**Issue by graymatter00** [aarol/variable-font-helper#1]
The [https://variable-font-helper.web.app/](https://variable-font-helper.web.app/) website has a checkbox in the **Configure** section labeled **Fine Tune**.  I can't see any reference to this checkbox in the instructions.  What does it do?

![image](https://user-images.githubusercontent.com/7201626/223324276-f8146722-dff1-4c3e-a4b4-e3dbe3907e08.png)

**Comment by aarol** [comment]
Hi! Sorry for responding so late. The fine tune checkbox just lets you move the slider in increments of one. For example, this way you can set the minimum weight to "225" (instead of "200" or "250") if you really want to.
